//Elements needed from html
let qwerty = document.getElementById('qwerty');
let phrase = document.getElementById('phrase');
let missed = 0; //if they miss 5 times, they lose
let scoreboard = document.querySelector('#scoreboard ol');
let overlay = document.getElementById('overlay');
let title = document.querySelector('#overlay .title');
let startButton = document.querySelector('.btn__reset');

//hide overlay

// declarations of Arrays
// Arrays generated by https://www.thegamegal.com/word-generator/
let phrases = [
    'smarty pants',
    'fit as a fiddle',
    'in the same boat',
    'ball is in your court',
    'today was a good day',
    'regulators mount up',
    'spongebob squarepants',
    'be the change',
    'on top of the world',
]
